### ISSUE TITLE
init command will produce incorrect yaml file

### ISSUE THREAD

**Issue by laizy** [cristianoliveira/funzzy#28]
run  "funzzy init" and then run "funzzy watch" will get some error:

`thread 'main' panicked at 'Unable to load configuration: ScanError { mark: Marker { index: 179, line: 8, col: 2
}, info: "while parsing a block mapping, did not find expected key" }', ../src/libcore\result.rs:799
rc/cli/init.rs`

it seems the `init` command produce incorrect .watch.yaml file: 
` run:'ls -a'`  should be  ` run: 'ls -a'` .

**Comment by cristianoliveira** [comment]
Hello @laizy 
Thanks for reporting this issue. Let me take a look.
