### ISSUE TITLE
bug: watcher triggers the run multiple times for a single change

### ISSUE THREAD

**Issue by marceloboeira** [cristianoliveira/funzzy#36]
```
- name: run my tests
  run: make test
  change: ['src/**', 'test/**']
```

I save the file on `src/index.js` and for some reason it runs the tests 5 times...

**Comment by cristianoliveira** [comment]
Apparently, the error was related to the different behaviour on the last versions of [OSX on notify lib](https://github.com/passcod/notify/blob/master/src/lib.rs) and it was fixed by the library itself. So was just a matter of updating it. :)

I'm going to release a new version with the fix.

**Comment by marceloboeira** [comment]
It's still happening...

**Comment by hu13** [comment]
@marceloboeira are you noticing it fewer times?
for me, it triggers twice.

@cristianoliveira can we increase the debounce time?

**Comment by cristianoliveira** [comment]
Hey @hu13 I'll have to take a look. I don't use the watcher as much as I used to. I'll take a look this weekend tho 😄
